// Generated by gencpp from file ros_qr_tracker/AddTarget.msg
// DO NOT EDIT!


#ifndef ROS_QR_TRACKER_MESSAGE_ADDTARGET_H
#define ROS_QR_TRACKER_MESSAGE_ADDTARGET_H

#include <ros/service_traits.h>


#include <ros_qr_tracker/AddTargetRequest.h>
#include <ros_qr_tracker/AddTargetResponse.h>


namespace ros_qr_tracker
{

struct AddTarget
{

typedef AddTargetRequest Request;
typedef AddTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTarget
} // namespace ros_qr_tracker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_qr_tracker::AddTarget > {
  static const char* value()
  {
    return "992ce8a1687cec8c8bd883ec73ca41d1";
  }

  static const char* value(const ::ros_qr_tracker::AddTarget&) { return value(); }
};

template<>
struct DataType< ::ros_qr_tracker::AddTarget > {
  static const char* value()
  {
    return "ros_qr_tracker/AddTarget";
  }

  static const char* value(const ::ros_qr_tracker::AddTarget&) { return value(); }
};


// service_traits::MD5Sum< ::ros_qr_tracker::AddTargetRequest> should match 
// service_traits::MD5Sum< ::ros_qr_tracker::AddTarget > 
template<>
struct MD5Sum< ::ros_qr_tracker::AddTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_qr_tracker::AddTarget >::value();
  }
  static const char* value(const ::ros_qr_tracker::AddTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_qr_tracker::AddTargetRequest> should match 
// service_traits::DataType< ::ros_qr_tracker::AddTarget > 
template<>
struct DataType< ::ros_qr_tracker::AddTargetRequest>
{
  static const char* value()
  {
    return DataType< ::ros_qr_tracker::AddTarget >::value();
  }
  static const char* value(const ::ros_qr_tracker::AddTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_qr_tracker::AddTargetResponse> should match 
// service_traits::MD5Sum< ::ros_qr_tracker::AddTarget > 
template<>
struct MD5Sum< ::ros_qr_tracker::AddTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_qr_tracker::AddTarget >::value();
  }
  static const char* value(const ::ros_qr_tracker::AddTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_qr_tracker::AddTargetResponse> should match 
// service_traits::DataType< ::ros_qr_tracker::AddTarget > 
template<>
struct DataType< ::ros_qr_tracker::AddTargetResponse>
{
  static const char* value()
  {
    return DataType< ::ros_qr_tracker::AddTarget >::value();
  }
  static const char* value(const ::ros_qr_tracker::AddTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_QR_TRACKER_MESSAGE_ADDTARGET_H
