// Generated by gencpp from file ros_qr_tracker/SetTarget.msg
// DO NOT EDIT!


#ifndef ROS_QR_TRACKER_MESSAGE_SETTARGET_H
#define ROS_QR_TRACKER_MESSAGE_SETTARGET_H

#include <ros/service_traits.h>


#include <ros_qr_tracker/SetTargetRequest.h>
#include <ros_qr_tracker/SetTargetResponse.h>


namespace ros_qr_tracker
{

struct SetTarget
{

typedef SetTargetRequest Request;
typedef SetTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTarget
} // namespace ros_qr_tracker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_qr_tracker::SetTarget > {
  static const char* value()
  {
    return "992ce8a1687cec8c8bd883ec73ca41d1";
  }

  static const char* value(const ::ros_qr_tracker::SetTarget&) { return value(); }
};

template<>
struct DataType< ::ros_qr_tracker::SetTarget > {
  static const char* value()
  {
    return "ros_qr_tracker/SetTarget";
  }

  static const char* value(const ::ros_qr_tracker::SetTarget&) { return value(); }
};


// service_traits::MD5Sum< ::ros_qr_tracker::SetTargetRequest> should match 
// service_traits::MD5Sum< ::ros_qr_tracker::SetTarget > 
template<>
struct MD5Sum< ::ros_qr_tracker::SetTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_qr_tracker::SetTarget >::value();
  }
  static const char* value(const ::ros_qr_tracker::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_qr_tracker::SetTargetRequest> should match 
// service_traits::DataType< ::ros_qr_tracker::SetTarget > 
template<>
struct DataType< ::ros_qr_tracker::SetTargetRequest>
{
  static const char* value()
  {
    return DataType< ::ros_qr_tracker::SetTarget >::value();
  }
  static const char* value(const ::ros_qr_tracker::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_qr_tracker::SetTargetResponse> should match 
// service_traits::MD5Sum< ::ros_qr_tracker::SetTarget > 
template<>
struct MD5Sum< ::ros_qr_tracker::SetTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_qr_tracker::SetTarget >::value();
  }
  static const char* value(const ::ros_qr_tracker::SetTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_qr_tracker::SetTargetResponse> should match 
// service_traits::DataType< ::ros_qr_tracker::SetTarget > 
template<>
struct DataType< ::ros_qr_tracker::SetTargetResponse>
{
  static const char* value()
  {
    return DataType< ::ros_qr_tracker::SetTarget >::value();
  }
  static const char* value(const ::ros_qr_tracker::SetTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_QR_TRACKER_MESSAGE_SETTARGET_H
