<?xml version='1.0'?>
<sdf version='1.4'>
	<model name="mobot" xmlns:xacro="http://www.ros.org/wiki/xacro">
		<xacro:property name="PI" value="3.1415926535897931"/>
		<xacro:property name="ChassisHeight" value = "0.1"/>
		<xacro:property name="ChassisLength" value = "0.4"/>
		<xacro:property name="ChassisWidth" value = "0.2"/>
		<xacro:property name="ChassisMass" value = "50"/>

		<xacro:property name="casterRadius" value = "0.05"/>
		<xacro:property name="casterMass" value = "5"/>
		
		<xacro:property name="WheelWidth" value = "0.05"/>
		<xacro:property name="WheelRadius" value = "0.1"/>
		<xacro:property name="WheelPos" value = "0.12"/>
		<xacro:property name="WheelMass" value = "5"/>
		<xacro:property name="WheelDamping" value = "1"/>

		<xacro:property name="cameraSize" value = "0.05"/>
		<xacro:property name="cameraMass" value = "0.1"/>

		<xacro:include filename="$(find /home/ion/catkin_ws/src/models/mobot_description
)/sdf/model.xacro"/>

		<static>True</static>
		<link name='chassis'>
			<pose>0 0 ${wheelRadius} 0 0 0</pose>
			<collision name='collision'>
				<geometry>
					<box>
						<size>${chassisLength} ${chassisWidth} ${chassisHeight}</size>
					</box>
				</geometry>
			</collision>
			
			<visual name='visual'>
				<geometry>
					<box>
						<size>${chassisLength} ${chassisWidth} ${chassisHeight}</size>
					</box>
				</geometry>
				<material>
					<script>
						<name>Gazebo/Red</name>
						<uri>__default</uri>
					</script>
				</material>
			</visual>

			<inertial>
				<mass>${chassisMass}</mass>
				<box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
			</inertial>
			
			<collision name='caster_collision'>
				<pose>${-chassisLength/3} 0 ${-chassisHeight/2} 0 0 0</pose>
				<geometry>
					<sphere>
						<radius>${casterRadius}</radius>
					</sphere>
				</geometry>

				<surface>
					<friction>
						<ode>
							<mu>0</mu>
							<mu2>0</mu2>
							<slip1>1.0</slip1>
							<slip2>1.0</slip2>
						</ode>
					</friction>
				</surface>
			</collision>
			
			<visual name='caster_visual'>
				<pose>${-chassisLength/3} 0 ${-chassisHeight/2} 0 0 0</pose>
				<geometry>
					<sphere>
						<radius>${casterRadius}</radius>
					</sphere>
				</geometry>
				<material>
					<script>
						<name>Gazebo/White</name>
						<uri>__default__</uri>
					</script>
				</material>
			</visual>
		</link>
	</model>
</sdf>
