set(ar_track_alvar_msgs_MESSAGE_FILES "/home/hammerviking/robotic_software/ardrone_moving_landing_platform/src/camera/ar_track_alvar/ar_track_alvar_msgs/msg/AlvarMarker.msg;/home/hammerviking/robotic_software/ardrone_moving_landing_platform/src/camera/ar_track_alvar/ar_track_alvar_msgs/msg/AlvarMarkers.msg")
set(ar_track_alvar_msgs_SERVICE_FILES "")
